version: "3.7"
services:

  # DATABASE
  postgres:
    image: postgres:13.1
    volumes:
      - next-markermap-database:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:4221:5432"
    env_file: ./env/.env.postgres

  # APP
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "3112:3000"
      - "5112:5555"
    env_file: ./env/.env.app
    stdin_open: true

volumes:
  next-markermap-database:
    name: next-markermap-database
